name: zstandard_platform_interface
description: A common platform interface for the zstandard plugin.
version: 1.4.2

homepage: https://vyp.dev
repository: https://github.com/vypdev/zstandard/tree/master/zstandard_platform_interface

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  kiri_check: ^1.3.1
  mutation_test: ^1.8.0