name: zstandard_ios
description: iOS platform implementation of zstandard
version: 1.4.2

homepage: https://vyp.dev
repository: https://github.com/vypdev/zstandard/tree/master/zstandard_ios

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  zstandard_platform_interface: ^1.4.2
  zstandard_native: ^1.4.2
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  kiri_check: ^1.3.1
  leak_tracker: ^11.0.0
  leak_tracker_testing: ^3.0.2
  mutation_test: ^1.8.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
        pluginClass: ZstandardIosPlugin