name: zstandard_platform_web_example
description: "Demonstrates how to use the zstandard_platform_web plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  zstandard_platform_interface: ^1.0.0
  zstandard_web:
    path: ../
  cupertino_icons: ^1.0.8
  web: ^1.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  kiri_check: ^1.3.1
  leak_tracker: ^11.0.0
  leak_tracker_testing: ^3.0.2

flutter:
  uses-material-design: true
