name: zstandard_cli
description: CLI implementation of zstandard. For desktops.
version: 1.4.2

homepage: https://vyp.dev
repository: https://github.com/vypdev/zstandard/tree/master/zstandard_cli

environment:
  sdk: ^3.6.0

dependencies:
  ffi: ^2.1.3
  path: ^1.9.1
  platform: ^3.1.6
  zstandard_native: ^1.4.2

dev_dependencies:
  coverage: ^1.9.0
  ffigen: ^11.0.0
  kiri_check: ^1.3.1
  leak_tracker: ^11.0.0
  leak_tracker_testing: ^3.0.2
  lints: ^6.1.0
  mutation_test: ^1.8.0
  test: ^1.24.0

platforms:
  linux:
  macos:
  windows:

screenshots:
  - description: 'Windows compression sample'
    path: images/windows_compression_sample.png
  - description: 'Windows decompression sample'
    path: images/windows_decompression_sample.png
  - description: 'macOS compression sample'
    path: images/macos_compression_sample.png
  - description: 'macOS decompression sample'
    path: images/macos_decompression_sample.png
  - description: 'Linux compression sample'
    path: images/linux_compression_sample.png
  - description: 'Linux decompression sample'
    path: images/linux_decompression_sample.png
