name: zstandard_web
description: Web platform implementation of zstandard
version: 1.3.32

homepage: https://vyp.dev
repository: https://github.com/vypdev/zstandard/tree/master/zstandard_web

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: zstandard
    platforms:
      web:
        pluginClass: ZstandardWeb
        fileName: zstandard_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  zstandard_platform_interface: ^1.3.32
  web: ">=1.0.0 <2.0.0"

dev_dependencies:
  kiri_check: ^1.3.1
  flutter_lints: ^6.0.0
  mutation_test: ^1.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16