name: Push Checks Linux

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!release/**'
      - '!hotfix/**'
      - '!master'
    #paths:
    #  - "zstandard_linux/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  check_linux_analyze:
    name: Analyze Linux
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_linux
        run: flutter pub get

      - name: Analyze check
        working-directory: zstandard_linux
        run: flutter analyze

  check_linux_test:
    name: Test Linux
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_linux
        run: flutter pub get

      - name: Test check
        working-directory: zstandard_linux
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: zstandard_linux/coverage/lcov.info
          flags: linux
          fail_ci_if_error: false

  check_linux_publish_dry_run:
    name: Dry Run Publish Linux
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_linux
        run: flutter pub get

      - name: Publish Dry Run
        working-directory: zstandard_linux
        run: dart pub publish --dry-run
