name: Push Checks Windows

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!release/**'
      - '!hotfix/**'
      - '!master'
    #paths:
    #  - "zstandard_windows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  check_windows_analyze:
    name: Analyze Windows
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: zstandard_windows
        shell: cmd
        run: flutter pub get

      - name: Analyze check
        working-directory: zstandard_windows
        shell: cmd
        run: flutter analyze

  check_windows_test:
    name: Test Windows
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: zstandard_windows
        shell: cmd
        run: flutter pub get

      - name: Unit tests
        working-directory: zstandard_windows
        shell: cmd
        run: flutter test --coverage

      - name: Get example dependencies
        working-directory: zstandard_windows/example
        shell: cmd
        run: flutter pub get

      - name: Run integration tests
        working-directory: zstandard_windows/example
        shell: cmd
        run: flutter test integration_test/ -d windows

      - name: Check coverage threshold (95%) and upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: zstandard_windows/coverage/lcov.info
          flags: windows
          fail_ci_if_error: true

  check_windows_publish_dry_run:
    name: Dry Run Publish Windows
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: zstandard_windows
        shell: cmd
        run: flutter pub get

      - name: Publish Dry Run
        working-directory: zstandard_windows
        shell: cmd
        run: dart pub publish --dry-run
