name: Push Checks Linux

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!release/**'
      - '!hotfix/**'
    #  - '!master'
    #paths:
    #  - "zstandard_linux/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: ${{ vars.FLUTTER_VERSION || '3.41.4' }}

jobs:
  check_linux_analyze:
    name: Analyze Linux
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Get dependencies
        working-directory: zstandard_linux
        run: flutter pub get

      - name: Analyze check
        working-directory: zstandard_linux
        run: flutter analyze

  check_linux_test:
    name: Test Linux
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Get dependencies
        working-directory: zstandard_linux
        run: flutter pub get

      - name: Get example dependencies
        working-directory: zstandard_linux/example
        run: flutter pub get

      - name: Run integration tests
        working-directory: zstandard_linux/example
        run: flutter test integration_test/ -d linux

  check_linux_publish_dry_run:
    name: Dry Run Publish Linux
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Get dependencies
        working-directory: zstandard_linux
        run: flutter pub get

      - name: Publish Dry Run
        working-directory: zstandard_linux
        run: dart pub publish --dry-run
