name: Push Checks CLI

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!release/**'
      - '!hotfix/**'
      - '!master'
    #paths:
    #  - "zstandard_cli/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_cli_analyze:
    name: Analyze CLI
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_cli
        run: dart pub get

      - name: Analyze check
        working-directory: zstandard_cli
        run: dart analyze

  check_cli_test:
    name: Test CLI
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_cli
        run: dart pub get

      - name: Test check
        working-directory: zstandard_cli
        run: dart test --coverage=coverage

      - name: Format coverage to lcov
        working-directory: zstandard_cli
        run: dart run coverage:format_coverage --lcov -i coverage -o coverage/lcov.info --packages=.dart_tool/package_config.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: zstandard_cli/coverage/lcov.info
          flags: cli
          fail_ci_if_error: false

  check_cli_publish_dry_run:
    name: Dry Run Publish CLI
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - name: Get dependencies
        working-directory: zstandard_cli
        run: dart pub get

      - name: Publish Dry Run
        working-directory: zstandard_cli
        run: dart pub publish --dry-run
        